service: svl-swapi
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:965972376463:table/usersTable

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get

  crearUsuario:
    handler: src/lambda/usuario/crearUsuario.crearUsuario
    events:
      - httpApi:
          path: /usuario
          method: post

  listarUsuarios:
    handler: src/lambda/usuario/listarUsuarios.listarUsuarios
    events:
      - httpApi:
          path: /usuario
          method: get

  obtenerUsuario:
    handler: src/lambda/usuario/obtenerUsuario.obtenerUsuario
    events:
      - httpApi:
          path: /usuario/{id}
          method: get

  actualizarUsuario:
    handler: src/lambda/usuario/actualizarUsuario.actualizarUsuario
    events:
      - httpApi:
          path: /usuario/{id}
          method: put

  eliminarUsuario:
    handler:  src/lambda/usuario/eliminarUsuario.eliminarUsuario
    events:
      - httpApi:
          path: /usuario/{id}
          method: delete

  listarPersonas:
    handler:  src/lambda/swapi/personas/listarPersonas.listarPersonas
    events:
      - httpApi:
          path: /swapi/persona
          method: get

  obtenerPersona:
    handler:  src/lambda/swapi/personas/obtenerPersona.obtenerPersona
    events:
      - httpApi:
          path: /swapi/persona/{id}
          method: get

  listarPlanetas:
    handler:  src/lambda/swapi/personas/listarPlanetas.listarPlanetas
    events:
      - httpApi:
          path: /swapi/planeta
          method: get

  obtenerPlaneta:
    handler:  src/lambda/swapi/personas/obtenerPlaneta.obtenerPlaneta
    events:
      - httpApi:
          path: /swapi/planeta/{id}
          method: get